form_uno:
    resource: "@FormUnoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app:
#     resource: '@AppBundle/Controller/'
#     type: annotation
web_encuesta:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /