form4validacionregistro_index:
    path:     /
    defaults: { _controller: "AppBundle:Form4validacionRegistro:index" }
    methods:  GET

form4validacionregistro_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Form4validacionRegistro:show" }
    methods:  GET

form4validacionregistro_new:
    path:     /new
    defaults: { _controller: "AppBundle:Form4validacionRegistro:new" }
    methods:  [GET, POST]

form4validacionregistro_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Form4validacionRegistro:edit" }
    methods:  [GET, POST]

form4validacionregistro_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Form4validacionRegistro:delete" }
    methods:  DELETE

form4validacionregistro_eliminar:
    path:     /{id}/eliminar
    defaults: { _controller: "AppBundle:Form4validacionRegistro:eliminar" }
