form_uno_homepage:
    path:     /formunoindex
    defaults: { _controller: FormUnoBundle:Default:index }

form_uno_new:
    path:     /formunonew
    defaults: { _controller: FormUnoBundle:Default:new }    

form_uno_insert:
    path:     /formunoinsert
    defaults: { _controller: FormUnoBundle:Default:insert }

form_uno_update:
    path:     /formunoupdate/{idfactor}
    defaults: { _controller: FormUnoBundle:Default:update }