AppBundle\Entity\Form3:
    type: entity
    table: form3
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        folioDep:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: folio_dep
        folioCodigoUe:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: folio_codigo_ue
        folioBoleta:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: folio_boleta
        p1Ue:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: p1_ue
        p2Nombres:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: p2_nombres
        p3Paterno:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: p3_paterno
        p4Materno:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: p4_materno
        p5Sexo:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: p5_sexo
        p6Edad:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: p6_edad
        p7Inscrito2016:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: p7_inscrito2016
        p8noUe:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: p8no_ue
        p9AnioEscolaridad2016:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: p9_anio_escolaridad2016
        p10AnioEscolaridad2018:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: p10_anio_escolaridad2018
        p11Rude:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: p11_rude
        p121Enfermedad:
            type: boolean
            nullable: true
            column: p121_enfermedad
        p121Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p121_importancia
        p122Accidente:
            type: boolean
            nullable: true
            column: p122_accidente
        p122Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p122_importancia
        p123Discapacidad:
            type: boolean
            nullable: true
            column: p123_discapacidad
        p123Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p123_importancia
        p124Edad:
            type: boolean
            nullable: true
            column: p124_edad
        p124Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p124_importancia
        p125Precocidad:
            type: boolean
            nullable: true
            column: p125_precocidad
        p125Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p125_importancia
        p126EmbarazoPaternidad:
            type: boolean
            nullable: true
            column: p126_embarazo_paternidad
        p126Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p126_importancia
        p127FormoHogar:
            type: boolean
            nullable: true
            column: p127_formo_hogar
        p127Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p127_importancia
        p128Abandono2016:
            type: boolean
            nullable: true
            column: p128_abandono2016
        p128Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p128_importancia
        p129Reprobacion2016:
            type: boolean
            nullable: true
            column: p129_reprobacion2016
        p129Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p129_importancia
        p1210InscricioCea:
            type: boolean
            nullable: true
            column: p1210_inscricio_cea
        p1210Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1210_importancia
        p1211Bulling:
            type: boolean
            nullable: true
            column: p1211_bulling
        p1211Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1211_importancia
        p1212UnidadDistante:
            type: boolean
            nullable: true
            column: p1212_unidad_distante
        p1212Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1212_importancia
        p1213UnidadNoOferta:
            type: boolean
            nullable: true
            column: p1213_unidad_no_oferta
        p1213Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1213_importancia
        p1214ResponsabilidadesHogar:
            type: boolean
            nullable: true
            column: p1214_responsabilidades_hogar
        p1214Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1214_importancia
        p1215TrasladoFamilia:
            type: boolean
            nullable: true
            column: p1215_traslado_familia
        p1215Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1215_importancia
        p1216FaltaApoyo:
            type: boolean
            nullable: true
            column: p1216_falta_apoyo
        p1216Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1216_importancia
        p1217NoViveHogarCompleto:
            type: boolean
            nullable: true
            column: p1217_no_vive_hogar_completo
        p1217Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1217_importancia
        p1218SeparacionHogar:
            type: boolean
            nullable: true
            column: p1218_separacion_hogar
        p1218Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1218_importancia
        p1219ViolenciaFamiliar:
            type: boolean
            nullable: true
            column: p1219_violencia_familiar
        p1219Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1219_importancia
        p1220FallecimientoFamiliar:
            type: boolean
            nullable: true
            column: p1220_fallecimiento_familiar
        p1220Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1220_importancia
        p1221FaltaDinero:
            type: boolean
            nullable: true
            column: p1221_falta_dinero
        p1221Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1221_importancia
        p1222Trabajo:
            type: boolean
            nullable: true
            column: p1222_trabajo
        p1222Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1222_importancia
        p1223TrabajoPadres:
            type: boolean
            nullable: true
            column: p1223_trabajo_padres
        p1223Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1223_importancia
        p1224Pandillas:
            type: boolean
            nullable: true
            column: p1224_pandillas
        p1224Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1224_importancia
        p1225Drogas:
            type: boolean
            nullable: true
            column: p1225_drogas
        p1225Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1225_importancia
        p1226Alcoholismo:
            type: boolean
            nullable: true
            column: p1226_alcoholismo
        p1226Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1226_importancia
        p1227Otra:
            type: boolean
            nullable: true
            column: p1227_otra
        p1227Importancia:
            type: string
            nullable: true
            length: 2
            options:
                fixed: false
            column: p1227_importancia
        p1227Razon:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
            column: p1227_razon
        p131TrabajaOtros:
            type: boolean
            nullable: true
            column: p131_trabaja_otros
        p132TrbajaPtopio:
            type: boolean
            nullable: true
            column: p132_trbaja_ptopio
        p133Ayuda:
            type: boolean
            nullable: true
            column: p133_ayuda
        p134Alimentos:
            type: boolean
            nullable: true
            column: p134_alimentos
        p135Vende:
            type: boolean
            nullable: true
            column: p135_vende
        p136Lava:
            type: boolean
            nullable: true
            column: p136_lava
        p137Cuida:
            type: boolean
            nullable: true
            column: p137_cuida
        p138Mineria:
            type: boolean
            nullable: true
            column: p138_mineria
        p139Otro:
            type: boolean
            nullable: true
            column: p139_otro
        p139Razon:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
            column: p139_razon
        p141Maniana:
            type: boolean
            nullable: true
            column: p141_maniana
        p142Tarde:
            type: boolean
            nullable: true
            column: p142_tarde
        p143Noche:
            type: boolean
            nullable: true
            column: p143_noche
        p151Trabaja:
            type: boolean
            nullable: true
            column: p151_trabaja
        p152Oferta:
            type: boolean
            nullable: true
            column: p152_oferta
        p153Lejos:
            type: boolean
            nullable: true
            column: p153_lejos
        p154LejosHogar:
            type: boolean
            nullable: true
            column: p154_lejos_hogar
        p155LejosUe:
            type: boolean
            nullable: true
            column: p155_lejos_ue
        p156Cansado:
            type: boolean
            nullable: true
            column: p156_cansado
        p157Ayudar:
            type: boolean
            nullable: true
            column: p157_ayudar
        p158Dinero:
            type: boolean
            nullable: true
            column: p158_dinero
        p159Apoyo:
            type: boolean
            nullable: true
            column: p159_apoyo
        p1510Otro:
            type: boolean
            nullable: true
            column: p1510_otro
        p15Razon:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
            column: p15_razon
        p16Papas:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
            column: p16_papas
        p17Vuelve2018:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
            column: p17_vuelve2018
        p18Companeros:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: p18_companeros
        p19Primera:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: p19_primera
        p19Segunda:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: p19_segunda
        p19Tercera:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: p19_tercera
        p19Cuarta:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: p19_cuarta
        p19Quinta:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: p19_quinta
        p19Otra:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
            column: p19_otra
        p20Nombre:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: p20_nombre
        p20Cargo:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: p20_cargo
    lifecycleCallbacks: {  }
